[package]
name = "ccc-link"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
ccc-target = { path = "../ccc-target" }
object.workspace = true
sha2.workspace = true

[target.'cfg(unix)'.dependencies]
signal-hook.workspace = true

[lints]
workspace = true
