//! C syntax tree construction over the ordered phase-7 token stream.

pub mod frontend;

/// A C keyword recognized after preprocessing.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Keyword {
    Auto,
    Break,
    Case,
    Char,
    Const,
    Continue,
    Default,
    Do,
    Double,
    Else,
    Enum,
    Extern,
    Float,
    For,
    Goto,
    If,
    Int,
    Inline,
    Long,
    Register,
    Restrict,
    Return,
    Short,
    Signed,
    Sizeof,
    Static,
    Struct,
    Switch,
    Typedef,
    Union,
    Unsigned,
    Void,
    Volatile,
    While,
    Alignas,
    Alignof,
    Atomic,
    Bool,
    Complex,
    Generic,
    Imaginary,
    Noreturn,
    StaticAssert,
    ThreadLocal,
    GnuThreadLocal,
    Asm,
    Attribute,
    Extension,
    Typeof,
}

impl Keyword {
    pub(crate) fn from_spelling(spelling: &str) -> Option<Self> {
        match spelling {
            "auto" => Some(Self::Auto),
            "break" => Some(Self::Break),
            "case" => Some(Self::Case),
            "char" => Some(Self::Char),
            "const" => Some(Self::Const),
            "continue" => Some(Self::Continue),
            "default" => Some(Self::Default),
            "do" => Some(Self::Do),
            "double" => Some(Self::Double),
            "else" => Some(Self::Else),
            "enum" => Some(Self::Enum),
            "extern" => Some(Self::Extern),
            "float" => Some(Self::Float),
            "for" => Some(Self::For),
            "goto" => Some(Self::Goto),
            "if" => Some(Self::If),
            "int" => Some(Self::Int),
            "inline" => Some(Self::Inline),
            "long" => Some(Self::Long),
            "register" => Some(Self::Register),
            "restrict" => Some(Self::Restrict),
            "return" => Some(Self::Return),
            "short" => Some(Self::Short),
            "signed" => Some(Self::Signed),
            "sizeof" => Some(Self::Sizeof),
            "static" => Some(Self::Static),
            "struct" => Some(Self::Struct),
            "switch" => Some(Self::Switch),
            "typedef" => Some(Self::Typedef),
            "union" => Some(Self::Union),
            "unsigned" => Some(Self::Unsigned),
            "void" => Some(Self::Void),
            "volatile" => Some(Self::Volatile),
            "while" => Some(Self::While),
            "_Alignas" => Some(Self::Alignas),
            "_Alignof" => Some(Self::Alignof),
            "_Atomic" => Some(Self::Atomic),
            "_Bool" => Some(Self::Bool),
            "_Complex" => Some(Self::Complex),
            "_Generic" => Some(Self::Generic),
            "_Imaginary" => Some(Self::Imaginary),
            "_Noreturn" => Some(Self::Noreturn),
            "_Static_assert" => Some(Self::StaticAssert),
            "_Thread_local" => Some(Self::ThreadLocal),
            "__asm" | "__asm__" => Some(Self::Asm),
            "__attribute" | "__attribute__" => Some(Self::Attribute),
            "__extension__" => Some(Self::Extension),
            "__typeof" | "__typeof__" => Some(Self::Typeof),
            "__const" | "__const__" => Some(Self::Const),
            "__inline" | "__inline__" => Some(Self::Inline),
            "__restrict" | "__restrict__" => Some(Self::Restrict),
            "__signed" | "__signed__" => Some(Self::Signed),
            "__volatile" | "__volatile__" => Some(Self::Volatile),
            "__alignof" | "__alignof__" => Some(Self::Alignof),
            "__thread" => Some(Self::GnuThreadLocal),
            _ => None,
        }
    }
}

/// A C punctuator recognized after preprocessing, including digraphs.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Punctuator {
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace,
    Comma,
    Semicolon,
    Colon,
    Question,
    Dot,
    Arrow,
    Ellipsis,
    Assign,
    PlusAssign,
    MinusAssign,
    StarAssign,
    SlashAssign,
    PercentAssign,
    LeftShiftAssign,
    RightShiftAssign,
    AmpAssign,
    CaretAssign,
    PipeAssign,
    Plus,
    Minus,
    PlusPlus,
    MinusMinus,
    Star,
    Slash,
    Percent,
    Bang,
    Tilde,
    Amp,
    Pipe,
    Caret,
    LeftShift,
    RightShift,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    EqualEqual,
    BangEqual,
    AmpAmp,
    PipePipe,
    Hash,
    HashHash,
    Unsupported,
}

impl Punctuator {
    pub(crate) fn from_spelling(spelling: &str) -> Self {
        match spelling {
            "(" => Self::LeftParen,
            ")" => Self::RightParen,
            "[" | "<:" => Self::LeftBracket,
            "]" | ":>" => Self::RightBracket,
            "{" | "<%" => Self::LeftBrace,
            "}" | "%>" => Self::RightBrace,
            "," => Self::Comma,
            ";" => Self::Semicolon,
            ":" => Self::Colon,
            "?" => Self::Question,
            "." => Self::Dot,
            "->" => Self::Arrow,
            "..." => Self::Ellipsis,
            "=" => Self::Assign,
            "+=" => Self::PlusAssign,
            "-=" => Self::MinusAssign,
            "*=" => Self::StarAssign,
            "/=" => Self::SlashAssign,
            "%=" => Self::PercentAssign,
            "<<=" => Self::LeftShiftAssign,
            ">>=" => Self::RightShiftAssign,
            "&=" => Self::AmpAssign,
            "^=" => Self::CaretAssign,
            "|=" => Self::PipeAssign,
            "+" => Self::Plus,
            "-" => Self::Minus,
            "++" => Self::PlusPlus,
            "--" => Self::MinusMinus,
            "*" => Self::Star,
            "/" => Self::Slash,
            "%" => Self::Percent,
            "!" => Self::Bang,
            "~" => Self::Tilde,
            "&" => Self::Amp,
            "|" => Self::Pipe,
            "^" => Self::Caret,
            "<<" => Self::LeftShift,
            ">>" => Self::RightShift,
            "<" => Self::Less,
            "<=" => Self::LessEqual,
            ">" => Self::Greater,
            ">=" => Self::GreaterEqual,
            "==" => Self::EqualEqual,
            "!=" => Self::BangEqual,
            "&&" => Self::AmpAmp,
            "||" => Self::PipePipe,
            "#" | "%:" => Self::Hash,
            "##" | "%:%:" => Self::HashHash,
            _ => Self::Unsupported,
        }
    }
}
