format_version = 1

enabled_targets = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu", "riscv64-unknown-linux-gnu", "aarch64-apple-darwin"]

corpora = ["bzip2", "c-ray", "csmith", "libc-headers", "lua", "redis", "sqlite", "zlib", "zstd"]
