[package]
name = "ccc-ir"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
ccc-pp = { path = "../ccc-pp" }
ccc-sema = { path = "../ccc-sema" }
ccc-session = { path = "../ccc-session" }
ccc-syntax = { path = "../ccc-syntax" }
ccc-types = { path = "../ccc-types" }

[dev-dependencies]
ccc-target = { path = "../ccc-target" }

[lints]
workspace = true
