[package]
name = "ccc-sema"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
ccc-diag = { path = "../ccc-diag" }
ccc-pp = { path = "../ccc-pp" }
ccc-session = { path = "../ccc-session" }
ccc-syntax = { path = "../ccc-syntax" }
ccc-target = { path = "../ccc-target" }
ccc-types = { path = "../ccc-types" }

[lints]
workspace = true
