[package]
name = "ccc-driver"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "ccc"
path = "src/main.rs"

[dependencies]
ccc-abi = { path = "../ccc-abi" }
ccc-codegen = { path = "../ccc-codegen" }
ccc-diag = { path = "../ccc-diag" }
ccc-ir = { path = "../ccc-ir" }
ccc-link = { path = "../ccc-link" }
ccc-pp = { path = "../ccc-pp" }
ccc-sema = { path = "../ccc-sema" }
ccc-session = { path = "../ccc-session" }
ccc-syntax = { path = "../ccc-syntax" }
ccc-target = { path = "../ccc-target" }
ccc-types = { path = "../ccc-types" }
object.workspace = true

[lints]
workspace = true
